### PR TITLE
Backoff when nsq is down

### LINKED ISSUE #21: use backoff logic when failing to publish to nsq
nsqd crashed on an instance, causing apexovernsq to retry in a loop until the disk filled, it would be good to have some backoff logic on error to prevent this happening

### PR DESCRIPTION
**Pull request by tealeg**
Fixes #21 

Use increasing backoffs (up to a limit) when we're unable to push messages over NSQ from the asynchronous handler.

Note, this will inevitably lead to the log channel filling more quickly.  Clients might be advised to increase the size of their channel.  I've also reduced what's logged locally in this circumstance to a single message each time the channel fills.

### CODE REVIEW

**Comment by tealeg** [comment]
@arussellsaw PTAL

File: producer.go [hunk 1]
```diff
@@ -168,10 +189,15 @@ func (h *AsyncApexLogNSQHandler) HandleLog(e *log.Entry) error {
...
 	case h.logChan <- e:
+		if h.logChanFull {
+			h.logChanFull = false
+		}
 		// Do nothing more
 	default:
-		backupLogger.Error("AsyncApexLogNSQHandler log channel is full")
-		backupLogger.Handler.HandleLog(e)
+		if !h.logChanFull {
+			backupLogger.Error("AsyncApexLogNSQHandler log channel is full")
```
Comment (arussellsaw) [inline producer.go]: we don't want to suppress this log line, i would keep complaining about the log channel being full

**Review by arussellsaw — CHANGES_REQUESTED** [review]

**Comment by arussellsaw** [comment]
sorry for missing this

**Comment by tealeg** [comment]
@arussellsaw PTAL - the checks have actually passed but for some reason GitHub isn't reflecting that.

File: producer.go [hunk 2]
```diff
@@ -106,48 +107,73 @@ type AsyncApexLogNSQHandler struct {
...
 func (h *AsyncApexLogNSQHandler) HandleLog(e *log.Entry) error {
 	h.mu.Lock()
+	defer h.mu.Unlock()
 
 	select {
 	case h.logChan <- e:
 		// Do nothing more
 	default:
 		backupLogger.Error("AsyncApexLogNSQHandler log channel is full")
-		backupLogger.Handler.HandleLog(e)
```
Comment (arussellsaw) [inline producer.go]: we should always log the entry to the backup logger, rather than just notifying that it's full

File: producer.go [hunk 3]
```diff
@@ -106,48 +107,73 @@ type AsyncApexLogNSQHandler struct {
...
 }
 
 func (h *AsyncApexLogNSQHandler) HandleLog(e *log.Entry) error {
 	h.mu.Lock()
+	defer h.mu.Unlock()
 
 	select {
 	case h.logChan <- e:
 		// Do nothing more
 	default:
```
Comment (arussellsaw) [inline producer.go]: perhaps for another PR, but perhaps rather than using `default:` here, a `time.After(100ms or something)` would be useful here. i don't think blocking to ensure we write the log line is a bad thing.

File: producer.go [hunk 4]
```diff
@@ -106,48 +107,73 @@ type AsyncApexLogNSQHandler struct {
...
+	}
+
+	handler := &AsyncApexLogNSQHandler{
+		logChan:  logChan,
+		stopChan: stopChan,
+	}
+
 	go func(cLog chan *log.Entry, cStop chan bool) {
 		var e *log.Entry
 		for {
```
Comment (arussellsaw) [inline producer.go]: by backing off in the for loop it means we discard log lines for temporariy failures. if instead you used the backoff pattern we've used elsewhere you can ensure temporary failures don't result in dropped messages.

https://play.golang.org/p/oKCavXlE4VH

File: producer.go [hunk 5]
```diff
@@ -106,48 +107,73 @@ type AsyncApexLogNSQHandler struct {
...
+					handler.mu.Lock()
+					backupLogger.WithField("backoff", time.Second*time.Duration(backoff)).WithError(err).Error("Publishing in AsyncApexLogNSQHander")
+					backoff = incrementBackoff(backoff)
+					handler.mu.Unlock()
+
 					continue
 				}
+				backoff = 0
 			case <-cStop:
 				break
```
Comment (arussellsaw) [inline producer.go]: the reason you are seeing race conditions even after calling `handler.Close()` is due to this break clause only breaking the select statement, not the outer loop. if you changed this to a return, or used a labeled loop/break you wouldn't need locking on the backupLogger calls

https://play.golang.org/p/p7tHx8JjFSY

fixed:

https://play.golang.org/p/FO8AGatNq5Y

**Review by arussellsaw — CHANGES_REQUESTED** [review]

File: producer.go (hunk 2 above)
Comment (tealeg) [reply producer.go]: Done

File: producer.go (hunk 3 above)
Comment (tealeg) [reply producer.go]: I'm not sure - you don't really know where you going to pay that price, or how often.

File: producer.go (hunk 5 above)
Comment (tealeg) [reply producer.go]: Done.

**Comment by tealeg** [comment]
@arussellsaw PTAL

**Comment by tealeg** [comment]
hold that thought.. new races.

File: producer.go [hunk 6]
```diff
@@ -106,39 +113,80 @@ type AsyncApexLogNSQHandler struct {
...
+		}
+		return newBackoff
+	}
+
+	handler := &AsyncApexLogNSQHandler{
+		logChan:  logChan,
+		stopChan: stopChan,
+	}
+
+	publishOrRetry := func(maxBackoff time.Duration, e *log.Entry) error {
```
Comment (arussellsaw) [inline producer.go]: i think this flow of declaring a bunch of functions as local variables makes this a bit hard to read. the one of ideas behind the retryBackoff() example was to separate retry code from the business logic. if your backoff logic was contained in it's own function, then passed `publish` as an anonymous function into that, i think this would be a lot clearer.

Comment (tealeg) [reply producer.go]: OK.. try now, it's a bit tidier.

**Review by arussellsaw — APPROVED** [review]
